### ISSUE TITLE
Заглавные буквы в названиях папок и текстр.

### ISSUE THREAD

**Issue by Wolf-Heart** [PavelBlend/stalker-resource-copier#1]
Отличная программа, лучшая из подобных, за что огромное спасибо!
Но есть баг. Некоторые названия папок и названия текстур начинаются с заглавных букв:
https://i.postimg.cc/L5t0LB0Q/1.png
https://i.postimg.cc/Gp6MfSWS/2.png
https://i.postimg.cc/Gm5zB5mh/3.png
https://i.postimg.cc/WzT7LRXS/4.png

**Comment by PavelBlend** [comment]
Скорее всего эти заглавные буквы прописаны в бинарных данных object файлов. Пока это единственная мысль, которая мне пришла в голову. Можешь скинуть мне несколько object файлов и level файл, чтобы я смог воспроизвести ошибку. Я думаю нет смысла скидывать прям всю rawdat'у, выбери только те объекты, которые используют текстуры из папок, имена которых начинаются с заглавных букв.

**Comment by Wolf-Heart** [comment]
Вот: https://yadi.sk/d/rYsr8jjdy8kEjw
Название папок - это название текстур с заглавными буквами, которые используют эти объекты.
Некоторые объекты, при поиске, повторялись и с другими текстурами с загл.буквами, я не стал их дублировать. Так что некоторые объекты могут использовать по две-три таких текстур.

**Comment by PavelBlend** [comment]
Я посмотрел, и так и оказалось, все имена папок берутся из object файлов, а в object файлах некоторые папки записаны с большой буквы. Могу унифицировать имена папок (сделать их все строчными буквами), так как для винды нет разницы в каком регистре написано имя. Там нужно будет одну строчку поменять (добавить вызов метода lower). Но я винду переустановил и у меня пока нет git'а. Завтра этим займусь, установлю всё.

**Comment by Wolf-Heart** [comment]
Да мне не особо срочно. Просто очень понравилась програмка своей простотой и быстротой использования, заметил баг и отписался. А прога просто замечательная. До этого пользовался для СоР resurce_copy на перл, а для SoC Pack Map Creator у обоих свои недостатки, но главный, это то что нужно две проги а не одна. Еще раз спасибо за програмку!!!

**Comment by PavelBlend** [comment]
@Wolf-Heart исправил. Зарелизил новую версию 0.0.3. Скачать:
https://github.com/PavelBlend/stalker-resource-copier/releases/tag/v0.0.3

**Comment by Wolf-Heart** [comment]
О... Оперативно. :+1:  
Спасибо!
